# Generated by Django 4.2.3 on 2023-08-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_manufacter_serie_user_user_type_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacter",
            new_name="Manufacturer",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacter",
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="API.manufacturer",
                verbose_name="Manufacturer",
            ),
            preserve_default=False,
        ),
    ]
