# Generated by Django 4.2.3 on 2023-09-01 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_rename_manufacter_manufacturer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProductImage",
        ),
    ]
