# Generated by Django 4.2.3 on 2023-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0005_alter_productimage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Images", to="API.productimage"
            ),
        ),
    ]
